version: '3'
services:
  # db:
  #   image: postgres:16.2-alpine
  #   container_name: EPITAsso_db
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #     timeout: 20s
  #     retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EPITAsso_backend
    command: python3 manage.py runserver 0.0.0.0:8000
    # restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db:
    #       condition: service_healthy

volumes:
  db_data: