services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py makemigrations &&
          python3 manage.py migrate --noinput &&
          python manage.py collectstatic --no-input &&
          gunicorn EPITAssoAPI.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    environment:
      ENV_FILE: .env.prod
    volumes:
      - static:/app/static
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/app/static
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - certbot

  certbot:
    image: certbot/certbot:v2.10.0
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    command: certonly --standalone --agree-tos --register-unsafely-without-email -d api.{DOMAIN_NAME}

volumes:
  db_data:
  static: