version: '3'

services:
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  redis:
    image: redis:7.4-rc1-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/data

volumes:
  db_data:
    driver: local
  redis_cache:
    driver: local