services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./backend/EPITAssoAPI/.env.prod

  django:
    build:
      context: ./backend/EPITAssoAPI
    command: >
      sh -c "python3 manage.py makemigrations &&
          python3 manage.py migrate --noinput &&
          python manage.py collectstatic --no-input &&
          gunicorn EPITAssoAPI.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - static:/app/static
    environment:
      ENV_FILE: .env.prod
    depends_on:
      - db

  asso:
    build:
      context: ./frontend/panel_asso
      dockerfile: Dockerfile.prod
    restart: always

  etd:
    build:
      context: ./frontend/vitrine
      dockerfile: Dockerfile.prod
    restart: always

  adm:
    build:
      context: ./frontend/panel_adm
      dockerfile: Dockerfile.prod
    restart: always

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - asso
      - etd
      - adm

volumes:
  db_data:
  static: