services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./backend/EPITAssoAPI/.env.prod
  
  redis:
    image: redis:7.4-rc1-alpine3.20
    volumes:
      - redis_cache:/data

  django-gunicorn:
    build:
      context: ./backend/EPITAssoAPI
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py makemigrations &&
          python3 manage.py migrate --noinput &&
          python manage.py collectstatic --no-input &&
          gunicorn EPITAssoAPI.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    environment:
      ENV_FILE: .env.prod
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - redis

  django-daphne:
    build:
      context: ./backend/EPITAssoAPI
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 EPITAssoAPI.asgi:application
    restart: always
    environment:
      ENV_FILE: .env.prod
      DJANGO_SETTINGS_MODULE: EPITAssoAPI.settings
    volumes:
      - static:/app/static
    depends_on:
      - db
      - redis

  asso:
    build:
      context: ./frontend/panel_asso
      dockerfile: Dockerfile.prod
    restart: always

  etd:
    build:
      context: ./frontend/vitrine
      dockerfile: Dockerfile.prod
    restart: always

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django-gunicorn
      - django-daphne
      - etd
      - asso

volumes:
  db_data:
  static:
  media:
  redis_cache: