# Generated by Django 5.0.4 on 2024-05-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("association", "0001_initial"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="post.post"
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="logo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="post.image"
            ),
        ),
    ]
