# Generated by Django 5.0.4 on 2024-06-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='association.association')),
            ],
        ),
    ]
