# Generated by Django 5.0.4 on 2024-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("association", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="webhook",
            field=models.URLField(blank=True, default=""),
        ),
    ]
