# Generated by Django 5.0.4 on 2024-09-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("association", "0004_association_slug_association_type_association_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="association.association",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberCommitment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hours", models.IntegerField()),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="association.commitment",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="association.associateuserandassociation",
                    ),
                ),
            ],
        ),
    ]
