# Generated by Django 5.0.4 on 2024-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_favorite_associations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='microsoft_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
