# Generated by Django 5.0.4 on 2024-06-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='associations_in_conversation',
            new_name='associations',
        ),
    ]
