# Generated by Django 5.0.4 on 2024-06-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_associations_in_conversation_conversation_associations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
    ]
