# Generated by Django 5.0.4 on 2024-06-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSheet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence', models.BooleanField(default=False)),
                ('resp', models.CharField(max_length=255)),
                ('tutor', models.CharField(max_length=255)),
                ('students_number', models.IntegerField()),
                ('members_number', models.IntegerField()),
                ('externals_number', models.IntegerField()),
                ('public_liability', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=255)),
                ('rooms_provided', models.CharField(blank=True, max_length=255, null=True)),
                ('present_equipments', models.CharField(blank=True, max_length=255, null=True)),
                ('drinks', models.CharField(blank=True, max_length=255, null=True)),
                ('special_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTaskList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('end_recurrence', models.DateTimeField()),
                ('recurrent', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(default=0)),
                ('places_number', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_authored', to=settings.AUTH_USER_MODEL)),
                ('other_associations', models.ManyToManyField(blank=True, related_name='related_events', to='association.association')),
                ('staff_members', models.ManyToManyField(blank=True, related_name='events_staff', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(blank=True, related_name='events', to='event.eventtasklist')),
                ('tags', models.ManyToManyField(blank=True, to='event.tag')),
            ],
        ),
    ]
