# Generated by Django 5.0.4 on 2024-05-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0002_initial'),
        ('event', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.post'),
        ),
        migrations.AddField(
            model_name='event',
            name='other_associations',
            field=models.ManyToManyField(blank=True, related_name='related_events', to='association.association'),
        ),
    ]
