# Generated by Django 5.0.4 on 2024-09-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("association", "0005_commitment_membercommitment"),
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMemberCommitment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hours", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members_commitments",
                        to="event.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_commitments",
                        to="association.associateuserandassociation",
                    ),
                ),
            ],
        ),
    ]
