# Generated by Django 5.0.4 on 2024-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[("event", "Event"), ("post", "Post")],
                default="post",
                max_length=5,
            ),
        ),
    ]
