# Generated by Django 5.0.4 on 2024-07-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("association", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="images")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association_image",
                        to="association.association",
                    ),
                ),
            ],
        ),
    ]
