name: Django CI
on:
  push:
    branches:
      - develop
      - master
      - feat/ci-cd
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/EPITAssoAPI/requirements.txt
      - name: Build
        run: python backend/EPITAssoAPI/manage.py check

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/EPITAssoAPI/requirements.txt
      - name: Set environment variable for CI
        run: echo "CI=True" >> $GITHUB_ENV
      - name: Run tests
        run: python backend/EPITAssoAPI/manage.py test

  lint_and_format:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Lint with ruff
      uses: chartboost/ruff-action@v1
      with:
        args: check --fix
        src: backend/EPITAssoAPI
    - name: Format with ruff
      uses: chartboost/ruff-action@v1
      with:
        args: format
        src: backend/EPITAssoAPI
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci: Format and lint code with ruff"
        add: "backend/EPITAssoAPI"
        author_name: "EPITAsso CI"
        tag_push: "--force-with-lease"