name: Django CI
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/EPITAssoAPI/requirements.txt
      - name: Build
        run: python backend/EPITAssoAPI/manage.py check

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/EPITAssoAPI/requirements.txt
      - name: Set environment variable for CI
        run: echo "CI=True" >> $GITHUB_ENV
      - name: Run tests
        run: python backend/EPITAssoAPI/manage.py test