name: Panel asso - Vue CI
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        cd frontend/panel_asso
        npm ci
    - name: Build
      run: |
        cd frontend/panel_asso
        npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        cd frontend/panel_asso
        npm ci
    - name: Test
      run: |
        cd frontend/panel_asso
        npm run test:unit
