name: Vitrine - Vue CI
on:
  push:
    branches:
      - develop
      - master
      - feat/ci-cd
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        cd frontend/vitrine
        npm ci
    - name: Build
      run: |
        cd frontend/vitrine
        npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        cd frontend/vitrine
        npm ci
    - name: Test
      run: |
        cd frontend/vitrine
        npm run test:unit

  lint_and_format:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        cd frontend/vitrine
        npm ci
    - name: Lint code
      run: |
        cd frontend/vitrine
        npm run lint
    - name: Format code
      run: |
        cd frontend/vitrine
        npm run format
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci(vitrine): Format and lint code"
        add: "frontend/vitrine"
        author_name: "EPITAsso CI"
        tag_push: "--force-with-lease"
